### ISSUE TITLE
Bower Support

### ISSUE THREAD

**Issue by PonteIneptique** [MadLittleMods/svg-curve-lib#1]
Hey there,
I love the plugin. Would you mind make it bower compatible so we can use it in other software on frontend easily ?

**Comment by MadLittleMods** [comment]
I added a `bower.json` file pointing to `src/js/svg-curve-lib.js`.

You should be able to install it with either of these commands now:

```
bower install MadLittleMods/svg-curve-lib
bower install git://github.com/MadLittleMods/svg-curve-lib.git
```

**Comment by PonteIneptique** [comment]
Thank you so much for that !
