### ISSUE TITLE
bower compatibility

### ISSUE THREAD

**Issue by tim42** [MadLittleMods/svg-curve-lib#2]
Thanks for your awesome library !! (you almost saved my life)(or kinda).
There is somehow two points that would make me even happier than I am right now:
- a license file (preferably MIT or LGPL-like). Right now, your repo is in the public domain
- a version 0.2.1 that include the bower.json file
- and, third point of that two points, a version 0.2.1 that's a bit more lightweight than 12Mib for ~3k lines of JS/C++ ;) (for the tag, you can create a new branch and remove everything that isn't code I believe)

Again, thanks for that great lib !! :)

**Comment by MadLittleMods** [comment]
> Code without an explicit license is protected by copyright and is by default All Rights Reserved. 
> 
> [Brian Doll, GitHub's VP of Marketing](http://stackoverflow.com/a/13669816/796832)

There is already `bower.json` present in the repo. See #1 

Most of the size came from the Visual Studio project in the test folder. I have added a `.gitignore` to that directory. The total size is now down to 190kb.

**Comment by tim42** [comment]
OK. I did not know for the default license on github.

What I was trying to explain is, by default, bower will checkout the latest _tag_ of a repo and as the latest tag on this repo (the 0.2.0) does not include the `bower.json` file, some tools (like gulp modules) won't correctly work even if bower downloads the repo.
There's a workaround this (as explained here: http://stackoverflow.com/q/15774649 ) but relaying on a commit sha/the master branch... is maybe not a so good practice. (but admittedly this works).

The command to install (the ones in #1 are not working correctly, `bower.json` not being present) should be:
`bower install MadLittleMods/svg-curve-lib#master`

**Comment by MadLittleMods** [comment]
@tim42 I added a new [release v0.2.0.1](https://github.com/MadLittleMods/svg-curve-lib/releases/tag/v0.2.0.1). Sorry for the inconvience.

**Comment by tim42** [comment]
thanks a lot !! :)
